backend:
  name: git-gateway
  branch: main  # Branch to deploy to, usually 'main'

media_folder: "static/uploads"  # Folder for storing media files like images
public_folder: "/uploads"  # The URL for media files

collections:
  - name: "blog"  # This is where your blog posts will be stored
    label: "Blog Posts"
    folder: "posts"  # Folder in your repo where blog posts will be saved
    create: true  # Allow users to create new posts
    slug: "{{year}}/{{month}}/{{day}}-{{slug}}"  # URL slug format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }  # Allow image uploads
